# Lab 02: Manipulate PyTorch Tensors -- exercise

In [2]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [36]:

# write your code here
A = torch.Tensor([[1, 2], [3, 4]])
B = torch.Tensor([10,20, 30, 40]).view(2, 2)
C = A + B
print(A)
print(B)
print(C)

tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20.],
        [30., 40.]])
tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [37]:

# write your code here
print(A.dim())


print(A.size())

print(A.type())


2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [41]:

# write your code here
A_Long = A.long()


print(A_Long.type())



torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [42]:

# write your code here

random = torch.rand(5, 2, 3)
print(random)

print(random.type())

print(random.size())

print(random.size(1))



tensor([[[0.9782, 0.9680, 0.1642],
         [0.6251, 0.4632, 0.3967]],

        [[0.0894, 0.6485, 0.9205],
         [0.2902, 0.2244, 0.7359]],

        [[0.8089, 0.3865, 0.3880],
         [0.1312, 0.4439, 0.5217]],

        [[0.7331, 0.8738, 0.3642],
         [0.0232, 0.8564, 0.7955]],

        [[0.3835, 0.6324, 0.8595],
         [0.9085, 0.8440, 0.1143]]])
torch.FloatTensor
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [45]:

# write your code here

A = torch.zeros(2,3,4,5)

print(A)



tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
